version: '3.7'

services:
  pg_db:
    build: 
      context: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - DBT_USER=dbt
      - DBT_PASSWORD=dbt
    ports:
      - "5432:5432"